/* Automatically generated by configure - do not modify! */
#ifndef FFMPEG_CONFIG_H
#define FFMPEG_CONFIG_H
#if defined(_WIN32)
#include "ffconfig_win32.h"
#else
#include "ffconfig_gcc.h"
#endif

#define  DEBUG
#endif /* FFMPEG_CONFIG_H */
